development:
  :name: onApp
  :email_address: onApp@tryingstuff.com
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: username
  :password: password
  :enable_starttls_auto: true
production:
  :name: onApp
  :email_address: onApp@tryingstuff.com
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: xxx
  :password: yyy
  :enable_starttls_auto: true
